New UI: snake skin
DeuxHuitHuit/symphonycms pull request #2
Opened 2017-04-05 18:51 UTC by alexnantel88

2017-04-05 21:13 UTC, nitriques requested changes

2017-04-05 21:13 UTC, nitriques commented on symphony/assets/css/src/installer.less
> +	position: relative; margin: 0 auto; padding: @spacing-smallish; max-width: @max-width-small;
Please use put each declaration on a new line ;)

2017-04-05 21:13 UTC, nitriques commented on symphony/assets/css/src/symphony.forms.less
> +.submit input[type="submit"] {
You found some input in a .submit container that was not a submit ?

2017-04-07 15:32 UTC, nitriques commented
Cool! We might wanna keep the red background around errors ?

2017-04-13 19:52 UTC, nitriques approved these changes

2017-04-13 19:55 UTC, nitriques requested changes

2017-04-13 19:55 UTC, nitriques commented on symphony/assets/js/src/backend.js
> +		};
Please check how we define "roots" at line 57. Can you remove that big ass object an only add the one or two that you need please ?

2017-04-13 19:55 UTC, nitriques commented on symphony/assets/js/src/backend.js
> +		/* Init - Show Subnav if parent active and highlight Subnav page if the case */
We try to never commit commented code, it's  bad practice :package:

2017-04-13 19:55 UTC, nitriques commented on symphony/assets/js/src/backend.js
> +			});
This should be done in PHP. Check the `__buildNavigation()` method in class.administrationpage.php

2017-04-14 17:43 UTC, nitriques approved these changes

2017-04-14 17:43 UTC, nitriques commented on symphony/assets/js/src/backend.js
Much better don't you think ? ;)

2017-04-14 17:47 UTC, nitriques requested changes

2017-04-14 17:47 UTC, nitriques commented on symphony/assets/js/src/backend.js
> +
This can be only

```js
// Header and Context
```

2017-04-19 18:13 UTC, nitriques requested changes

2017-04-19 18:13 UTC, nitriques commented on symphony/lib/toolkit/class.administrationpage.php
>                  $xGroup->appendChild($xGroupLabel);
Please also use multiple lines for this. And always add curly brakets.

2017-06-01 06:58 UTC, animaux commented
Thanks for all the great work you guys put into this!

By permission of @nitriques I will try to give some feedback. I will also try to be as objective as possible, but as things go with design stuff there is always a great deal of things that depend more on taste than anything else.

I know this is work in progress, so please excuse me if I go too far `:)`

## Nice

+ Roboto and apparent material design inspired approach
+ Clean and minimal
+ Top-right save button and back-arrow for current section

## UI-design issues

+ Light font weight seems finicky on non-retina devices
+ Fieldset labels in caps are hard to read und get longish
+ header h1 background orb seems unneccessary
+ site titles of medium length already breaks the layout
+ input fields feel inverted, when following the brighter=more-important dogma

## Minor UI-design issues

+ Gray text contrast seems to low (already on @nitriques’ radar)
+ Fieldset legends seem oversized (when in »blue mode«)
+ Fieldset labels in caps are hard to read 

## Possibly a question of subjective taste?

+ Our customers are always very fond of the simplicity of the current UI. The fact that everything important can be found in the main horizontal nav makes it very clean. I do like the fact that the new vertical navigation shows everything at once, but the page feels much more cluttered in L-form.
+ Using lines as dividers: I feel this could lean more towards the concept of structure/layers/areas in the [material design guidelines](https://material.io/guidelines/layout/structure.html).
+ border-radius and padding seems to large on inputs and sections. Maybe we should consider [material design](https://material.io/guidelines/components/text-fields.html#text-fields-input-types) here too?

Since you have been going the Roboto-way I wonder if there aren’t a lot more design-cues from the Material design guidelines we could implement. Even though I don’t even own an android device I strongly feel that the whole visual and ux-approach seems to be a lot more consistent and thought through than f. e. iOS 7+.

2019-03-29 21:38 UTC, closed without merging